services:
  - type: web
    name: neuroscan-ai
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    buildCommand: docker build -t neuroscan-ai .
    startCommand: docker run -p $PORT:$PORT neuroscan-ai
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000 