services:
  - type: web
    name: neuroscan-ai
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    buildCommand: docker build -t neuroscan-ai .
    startCommand: docker run -p $PORT:8501 neuroscan-ai
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0 